# Types
- name: "type: bug"
  color: "7AE5B4"
  description: "Something isn't working"
  from_name: "bug"
- name: "type: documentation"
  color: "7AE5B4"
  description: "Improvements or additions to documentation"
  from_name: "documentation"
- name: "type: dependency-upgrade"
  color: "7AE5B4"
  description: "Pull requests that update a dependency file"
  from_name: "dependency-upgrade"
- name: "type: enhancement"
  color: "7AE5B4"
  description: "New feature or request"
  from_name: "enhancement"
- name: "type: question"
  color: "7AE5B4"
  description: "A question about the workings of the tool"
  from_name: "question"
- name: "type: internal"
  color: "7AE5B4"
  description: "Miscellaneous non-functional changes such as refactorings and typos"
  from_name: "internal"
- name: "type: tests"
  color: "7AE5B4"
  description: "New and/or updates to existing tests"
  from_name: "tests"
- name: "type: regression"
  color: "7AE5B4"
  description: "A regression from a previous release"

# Impacts
- name: "impact: breaking-change"
  color: "E58070"
  description: "A change that is not backward compatible"
  from_name: "breaking-change"

# Statuses
- name: "status: blocked"
  color: "0366D6"
  description: "We can't proceed until some other issue is resolved"
- name: "status: declined"
  color: "0366D6"
  description: "This will not be worked on"
  from_name: "wontfix"
- name: "status: duplicate"
  color: "0366D6"
  description: "This issue or pull request already exists"
  from_name: "duplicate"
- name: "status: waiting-for-feedback"
  color: "0366D6"
  description: "Additional information is needed in order to proceed"
