version-template: $MAJOR.$MINOR.$PATCH.RELEASE
name-template: v$RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
categories:
  - title: ⭐ New Features
    labels:
      - 'type: enhancement'
  - title: 🐞 Bug Fixes
    labels:
      - 'type: bug'
      - 'type: regression'
  - title: 📔 Documentation
    labels:
      - 'type: documentation'
  - title: 🔨 Maintenance
    labels:
      - 'type: dependency-upgrade'
      - 'type: internal'
      - 'type: tests'
sort-by: title
sort-direction: ascending
version-resolver:
  major:
    labels:
      - 'impact: breaking-change'
  minor:
    labels:
      - 'type: enhancement'
  patch:
    labels:
      - 'type: documentation'
      - 'type: bug'
      - 'type: dependency-upgrade'
      - 'type: internal'
      - 'type: regression'
      - 'type: tests'
  default: patch
template: |
  $CHANGES
