name: label-maker

on:
  pull_request:
    paths:
      - '.github/workflows/label-maker.yml'
      - '.github/labels.yml'
  push:
    paths:
      - '.github/workflows/label-maker.yml'
      - '.github/labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Syncronize labels (dry-run)
        if: github.ref != 'refs/heads/main'
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - name: Synchronize labels
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
