name: Build master-branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 9
        uses: actions/setup-java@v2
        with:
          java-version: 1.9

      - name: Build with Maven
        run: mvn -B verify

  yaml_lint:
    name: YAML lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Validate YAML files
        uses: ibiqlik/action-yamllint@v3

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [build, yaml_lint]

    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
