name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Extract release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Install GPG key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
          server-id: sonatype-nexus
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish to Sonatype
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn \
            clean deploy \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -Drevision=${{ env.RELEASE_VERSION }} \
